name: Deploy to AWS
on:
  push:
    branches: [ main ]

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::501957928859:role/githubOpenIDIdPRole
          aws-region: us-east-1

      - name: Verify AWS Identity (Role)
        run: aws sts get-caller-identity
      - name: Deploy
        run: aws ec2 describe-instances